using System.IO;
using System.Text;
using Craftwar.Import;
using Craftwar.Sim;
using UnityEditor;
using UnityEngine;

namespace Craftwar.EditorTools
{
    /// <summary>
    /// Generates the default stat tables in the Sim assembly from the user's
    /// Battle.net Edition data files (unitdata.dat / upgrades.dat — raw UDTA /
    /// UGRD payloads without the leading word). BNE is the balance ground
    /// truth per project decision; values are game mechanics/facts.
    /// Batch: -executeMethod Craftwar.EditorTools.DataCodegen.Run
    /// </summary>
    public static class DataCodegen
    {
        const string OutputPath = "Assets/Scripts/Sim/Data/Generated/DefaultData.gen.cs";

        [MenuItem("Craftwar/Setup/Generate Default Stat Tables")]
        public static void Run()
        {
            string dataDir = FindBneDataDir();
            if (dataDir == null)
            {
                Debug.LogError("[Craftwar] Could not locate BNE data dir (unitdata.dat). " +
                               "Set mapsDir in LocalAssetPaths.json to the BNE x86\\Maps folder.");
                if (Application.isBatchMode) EditorApplication.Exit(1);
                return;
            }

            var units = UdtaParser.Parse(
                File.ReadAllBytes(Path.Combine(dataDir, "unitdata.dat")), hasLeadingWord: false);
            var upgrades = UgrdParser.Parse(
                File.ReadAllBytes(Path.Combine(dataDir, "upgrades.dat")), hasLeadingWord: false);

            // Sanity anchors before we bake anything.
            Require(units[(int)UnitTypeId.Footman].Hp == 60, "Footman HP 60");
            Require(units[(int)UnitTypeId.TownHall].Hp == 1200, "Town Hall HP 1200");
            Require(units[(int)UnitTypeId.Footman].GoldCost == 600, "Footman 600 gold");
            Require(upgrades[0].Gold == 800 && upgrades[1].Gold == 2400, "Sword upgrade costs");

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));
            File.WriteAllText(OutputPath, Emit(units, upgrades), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputPath);
            Debug.Log($"[Craftwar] Generated {OutputPath} from {dataDir}");
        }

        static void Require(bool cond, string what)
        {
            if (!cond)
                throw new System.InvalidOperationException($"Stat sanity check failed: {what}");
        }

        static string FindBneDataDir()
        {
            var paths = LocalAssetPaths.Load();
            if (paths != null && !string.IsNullOrEmpty(paths.mapsDir))
            {
                string x86 = Path.GetDirectoryName(paths.mapsDir);
                if (x86 != null)
                {
                    foreach (string sub in new[] { "Data\\Rez", "Data\\Files" })
                    {
                        string dir = Path.Combine(x86, sub);
                        if (File.Exists(Path.Combine(dir, "unitdata.dat")))
                            return dir;
                    }
                }
            }
            return null;
        }

        static string Emit(UnitTypeData[] units, UpgradeData[] upgrades)
        {
            var sb = new StringBuilder(256 * 1024);
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Craftwar.EditorTools.DataCodegen from the user's");
            sb.AppendLine("// Warcraft II Battle.net Edition data (UDTA/UGRD stat tables).");
            sb.AppendLine("// Do not edit by hand — rerun Craftwar/Setup/Generate Default Stat Tables.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace Craftwar.Sim");
            sb.AppendLine("{");
            sb.AppendLine("    public static class DefaultData");
            sb.AppendLine("    {");
            sb.AppendLine("        public static UnitTypeData[] BuildUnits() => new[]");
            sb.AppendLine("        {");
            for (int i = 0; i < units.Length; i++)
            {
                ref var u = ref units[i];
                string name = System.Enum.IsDefined(typeof(UnitTypeId), (byte)i)
                    ? ((UnitTypeId)i).ToString() : $"0x{i:x2}";
                sb.Append("            // 0x").Append(i.ToString("x2")).Append(' ').AppendLine(name);
                sb.Append("            new UnitTypeData { ");
                sb.Append($"Sight = {u.Sight}, Hp = {u.Hp}, HasMagic = {Bool(u.HasMagic)}, ");
                sb.Append($"BuildTime = {u.BuildTime}, GoldCost = {u.GoldCost}, LumberCost = {u.LumberCost}, OilCost = {u.OilCost}, ");
                sb.Append($"SizeW = {u.SizeW}, SizeH = {u.SizeH}, BoxW = {u.BoxW}, BoxH = {u.BoxH}, ");
                sb.Append($"AttackRange = {u.AttackRange}, ReactRangeComputer = {u.ReactRangeComputer}, ReactRangeHuman = {u.ReactRangeHuman}, ");
                sb.Append($"Armor = {u.Armor}, RectSelectable = {Bool(u.RectSelectable)}, Priority = {u.Priority}, ");
                sb.Append($"BasicDamage = {u.BasicDamage}, PiercingDamage = {u.PiercingDamage}, ");
                sb.Append($"WeaponsUpgradable = {Bool(u.WeaponsUpgradable)}, ArmorUpgradable = {Bool(u.ArmorUpgradable)}, ");
                sb.Append($"MissileWeapon = {u.MissileWeapon}, MoveDomain = {u.MoveDomain}, DecayRate = {u.DecayRate}, Annoy = {u.Annoy}, ");
                sb.Append($"RightClickAction = {u.RightClickAction}, PointValue = {u.PointValue}, CanTarget = {u.CanTarget}, ");
                sb.Append($"Flags = (UnitTypeFlags)0x{(uint)u.Flags:x8}u");
                sb.AppendLine(" },");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static UpgradeData[] BuildUpgrades() => new[]");
            sb.AppendLine("        {");
            for (int i = 0; i < upgrades.Length; i++)
            {
                ref var g = ref upgrades[i];
                sb.Append("            new UpgradeData { ");
                sb.Append($"Time = {g.Time}, Gold = {g.Gold}, Lumber = {g.Lumber}, Oil = {g.Oil}, ");
                sb.Append($"Icon = {g.Icon}, Group = {g.Group}, Flags = 0x{g.Flags:x8}u");
                sb.AppendLine(" }, // 0x" + i.ToString("x2"));
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        static string Bool(bool b) => b ? "true" : "false";
    }
}
